name: Build the embedded_reflash

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target: ["armv6", "armv7"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build embedded_reflash for armv6
        run: GOARCH=arm GOARM=6,softfloat go build -ldflags="-s -w" -o build/embedded_reflash-armv6

      - name: Build embedded_reflash for armv7
        run: GOARCH=arm GOARM=7,softfloat go build -ldflags="-s -w" -o build/embedded_reflash-armv7

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: embedded_reflash-${{ matrix.target }}
          path: build
